;;------------------------------------------------------------------------------
;; Game: FFVI Brave New World
;; Platform: SNES
;; Region: USA [!]
;;------------------------------------------------------------------------------

;comment patches to deactivate them

incsrc "reserved_freespace.asm"
incsrc "descriptions.asm"
incsrc "shrinked_colosseum.asm"
incsrc "reversible_bets.asm"
incsrc "veldt-freebies.asm"
incsrc "lore_curative.asm"
incsrc "noexp_overhaul.asm"
incsrc "bushido.asm"
incsrc "longer_skills.asm"
incsrc "esper_menu.asm"
incsrc "esper_transfer.asm"
incsrc "item.asm"
incsrc "scripts.asm"
incsrc "wallchange.asm"
incsrc "ragedance_descriptions.asm"
incsrc "party.asm"
incsrc "ailments_icons.asm"
incsrc "halfturn_blitz.asm"
incsrc "exploder.asm"
incsrc "mastered.asm"
incsrc "better_flags.asm"
incsrc "location_names.asm"
incsrc "events.asm"
incsrc "colored_counters.asm"
incsrc "save.asm"
incsrc "summon_xmagic.asm"
incsrc "rage_checklist.asm"
incsrc "intangir_fix.asm"
incsrc "mp_colors.asm"
incsrc "native_dance.asm"
incsrc "item_command.asm"
incsrc "double-counter.asm"
incsrc "sap_regen_rerise.asm"
incsrc "misc.asm"
incsrc "new_status.asm"
incsrc "arrange_elements_routine.asm"
incsrc "pushing_Y_sprite.asm"
incsrc "shop.asm"
incsrc "equip_menu.asm"
incsrc "magic.asm"
incsrc "custom_equip_sort.asm"
incsrc "near_fatal_zinger_clear.asm"
incsrc "double_meteor_fix.asm"
incsrc "C3FC20-C3F277.asm"
incsrc "free_equip_relic.asm"
incsrc "rage_s.asm"
incsrc "nowea-hard-selector.asm"
;incsrc "choreography.asm"
;incsrc "fft.asm"
;incsrc "new_intro.asm"
;incsrc "scan_anytime.asm"
