;;------------------------------------------------------------------------------
;; Game: FFVI Brave New World
;; Platform: SNES
;; Region: USA [!]
;;------------------------------------------------------------------------------

;comment patches to deactivate them

incsrc "reserved_freespace.asm"
incsrc "descriptions.asm"
;incsrc "vnw_descriptions.asm"
incsrc "shrinked_colosseum.asm"
incsrc "reversible_bets.asm"
incsrc "veldt-freebies.asm"
incsrc "lore_curative.asm"
incsrc "noexp_overhaul.asm"
incsrc "bushido.asm"
incsrc "longer_skills.asm"
incsrc "esper_menu.asm"
incsrc "esper_transfer.asm"
incsrc "item.asm"
;incsrc "vnw_item.asm"
incsrc "scripts.asm"
;incsrc "vnw_scripts.asm"
incsrc "monster_special.asm"
;incsrc "vnw_monster_special.asm"
incsrc "wallchange.asm"
incsrc "ragedance_descriptions.asm"
incsrc "party.asm"
incsrc "ailments_icons.asm"
incsrc "halfturn_blitz_stumble.asm"
incsrc "battle-info-modes.asm"
incsrc "exploder.asm"
incsrc "mastered.asm"
incsrc "better_flags.asm"
incsrc "location_names.asm"
incsrc "events.asm"
incsrc "cyans_uneventful_dream.asm"
incsrc "flashy_counters_v2.asm"
incsrc "save.asm"
incsrc "summon_xmagic.asm"
incsrc "rage_checklist.asm"
incsrc "intangir_fix.asm"
incsrc "mp_and_new_reflect_colour.asm"
incsrc "choreography.asm"
incsrc "native_dance.asm"
incsrc "item_command.asm"
incsrc "double-counter.asm"
incsrc "phantasm.asm"
incsrc "misc.asm"
incsrc "arrange_elements_routine.asm"
incsrc "new_status.asm"
incsrc "custom_equip_sort.asm"
incsrc "pushing_Y_sprite.asm"
incsrc "shop.asm"
incsrc "equip_menu.asm"
incsrc "magic.asm"
incsrc "double_meteor_fix.asm"
incsrc "C3FC20-C3F277.asm"
incsrc "free_equip_relic.asm"
incsrc "Skill.asm"
incsrc "tick-calc.asm"
incsrc "hold-b-advance-text.asm"
incsrc "thanks.asm"
incsrc "summon_indicator.asm"
incsrc "custom_animations.asm"
incsrc "phoenix_fix.asm"
incsrc "undead_skin.asm"
incsrc "zombie_sprites.asm"
incsrc "cool_berserk.asm"
incsrc "new_events.asm"
